name: Static analysis

# Including pull_request is necessary for the workflow to show up under Checks for PRs from forks into upstream.
on: [push, pull_request]

jobs:
  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.21.0
    permissions:
      contents: read
